if status is-interactive
    # Commands to run in interactive sessions can go here
end

source ~/.config/envman/PATH.env

set -g fish_key_bindings fish_vi_key_bindings

# Generated for envman. Do not edit.
test -s ~/.config/envman/load.fish; and source ~/.config/envman/load.fish

# Generated for envman. Do not edit.
test -s "$HOME/.config/envman/load.fish"; and source "$HOME/.config/envman/load.fish"

# added by Webi for pyenv
status is-login; and pyenv init --path | source
status is-interactive; and pyenv init - | source

zoxide init fish | source


# Generated by Webi. Do not edit.
webi --init fish | source
